baseurl: /thesis

collections:
  artists:
    output: true
    permalink: /:collection/:path/
  albums:
    output: true
    permalink: /:collection/:path/
  artist_info:
    output: true
    permalink: /:collection/:path/


defaults:
  - scope:
      path: ""
      type: artists
    values:
      layout: artist
  - scope:
      path: ""
      type: artist_info
    values:
      layout: default
  - scope:
      path: ""
      type: albums
    values:
      layout: default
